package snow.app.padelbook.network.responses.clubList

data class ClubData(
    val aminities_id: String,
    val city: String,
    val club_id : String,
    val club_name: String,
    val country: String,
    val court_time: List<CourtTime>,
    val description: String,
    val favourite_status: Boolean,
    val club_image: String,
    val latitude : Double,
    val longitude : Double,
    val phone: String,
    val postal_code: String,
    val price_per_person: String,
    val rating: Int,
    val state: String,
    val status: String,
    val is_favourite: Int,
    val street: String,
    val total_rating: Int,
    val user_id: String,
    val website: String,
    val address: String,
    val booking_type: String,
    val club_details_id: String,
    val court_id: String,
    val date: String,
    val start_time : String,
    val time : String,
    val distance: String,
    val match_id: String,
    val court_feature: String,
    val participant_list: List<Participant>,
    val schedule_id: Int,
)